[package]
name = "template_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.85"
anyhow = "1.0.86"
quote = "1.0.36"
which = "6.0.1"
walkdir = "2.5.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
itertools = "0.13.0"
