[package]
name = "template_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.66"
anyhow = "1.0.75"
quote = "1.0.33"
which = "4.4.2"
walkdir = "2.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
