name: Test
on:
  pull_request:

jobs:
  create-shards:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      shards: ${{ steps.shards.outputs.shards }}
      shard-count: ${{ steps.shards.outputs.count }}
    steps:
      - id: shards
        run: |
          shard_count=6

          echo "count=[$shard_count]" >> $GITHUB_OUTPUT
          max_shard=$((shard_count - 1))
          echo "shards=[$(seq -s ', ' 0 $max_shard)]" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: create-shards
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.create-shards.outputs.shards) }}
        shard-count: ${{ fromJson(needs.create-shards.outputs.shard-count) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          save-always: true
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        run: |
          rustup toolchain install stable --component rustfmt

      - name: Install pnpm
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
        with:
          version: ^11.20.0
          runtime: node@lts
          install: false
      - name: Test
        run: cargo test
        env:
          SHARD: ${{ matrix.shard }}
          SHARD_COUNT: ${{ matrix.shard-count }}
