name: Update Dependencies
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Detect open PR
        id: detect_open_pr
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              base: 'main',
              head: `${context.repo.owner}:updates`,
            });
            console.log(pullRequests)
            console.log(pullRequests[0]?.head?.ref, pullRequests[0]?.number)
            return { name: pullRequests[0]?.head?.ref ?? 'main', issue_number: pullRequests[0]?.number };

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.detect_open_pr.outputs.result.name }}

      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Do updates
        run: |
          {
            echo 'PR_BODY<<EOF'
            node ./.github/workflows/update_deps.mjs
            echo EOF
          } >> $GITHUB_ENV

      - name: Open PR
        if: steps.detect_open_pr.outputs.result.name == 'main'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.create_token.outputs.token }}
          commit-message: '[ci] Update dependencies'
          title: Update dependencies
          body: ${{ env.PR_BODY }}
          branch: updates

      - name: Push to existing PR
        if: steps.detect_open_pr.outputs.result.name != 'main'
        run: |
          if git diff --quiet; then
            echo "No changes"
            exit 1
          fi
          git add .

          git config --local user.email "create-o7-app@users.noreply.github.com"
          git config --local user.name "create-o7-app[bot]"
          git commit -m "[ci] Update dependencies"

          git push origin updates
      - name: Comment on PR
        if: steps.detect_open_pr.outputs.result.name != 'main'
        uses: actions/github-script@v4
        with:
          github-token: ${{ steps.create_token.outputs.token }}
          script: |
            github.issues.createComment({
              issue_number: ${{ steps.detect_open_pr.outputs.result.issue_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.PR_BODY,
            });
